server:
  port: 9001
#  jdbc related properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true